services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    environment:
      - VITE_MESSAGES_PER_MONTH_FREE=${VITE_MESSAGES_PER_MONTH_FREE:-100}
      - VITE_MESSAGES_PER_MONTH_PAID=${VITE_MESSAGES_PER_MONTH_PAID:-1500}
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      - DATABASE_URL=mongodb://root:pass@db:27017
      - VALKEY_URL=redis://kv:6379

      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-}
      - BASE_URL=${BASE_URL:-}

      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID:-}

      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}

      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - EXA_API_KEY=${EXA_API_KEY:-}
      - GITHUB_PAT=${GITHUB_PAT:-}

      - VITE_MESSAGES_PER_MONTH_FREE=${VITE_MESSAGES_PER_MONTH_FREE:-100}
      - VITE_MESSAGES_PER_MONTH_PAID=${VITE_MESSAGES_PER_MONTH_PAID:-1500}

      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        ['CMD-SHELL', 'echo ''db.runCommand("ping").ok'' | mongosh localhost:27017/test --quiet']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  kv:
    image: redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  mongo_data:
