services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      - DATABASE_URL=mongodb://root:pass@db:27017
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
      - FIRECRAWL_API_URL=${FIRECRAWL_API_URL:-}
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - SERP_API_KEY=${SERP_API_KEY:-}
      - GITHUB_PAT=${GITHUB_PAT:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        ['CMD-SHELL', 'echo ''db.runCommand("ping").ok'' | mongosh localhost:27017/test --quiet']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  mongo_data:
