name: Continuous Integration

on: [push, pull_request]

jobs:
  types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check types
        run: bun type-check

  prettier:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code style
        run: bun prettier

  es-lint:
    name: Check ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check ESLint
        run: bun lint
